### PR TITLE
Add .gitignore with iml files and .idea directories ignored

### PR DESCRIPTION
**Pull request by Anirudh94**

### CODE REVIEW

**Comment by jiekang** [comment]
What's the **/ part for? Doesn't using just
*.iml
.idea

also work?

**Comment by Anirudh94** [comment]
**/ means any depth in including the current directory. In my case I set it up so I have intellij project just for boreas/web-layer so I added it. Alternatively I can be more specific and add it as:
```
web-layer/*.iml
web-layer/.idea
```
What's your setup like?

**Comment by Anirudh94** [comment]
Oh nvm, I thought you **must** specify directory level so I put `**/` to say any directory level in. I'll change it now

**Comment by Anirudh94** [comment]
@jiekang thoughts?

**Comment by Anirudh94** [comment]
ok i'm gonna go ahead and merge

**Comment by jiekang** [comment]
Oops; didn't notice the comments till now... Looks good.

**Pull request merged**
